# farmers/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('farmers/', views.farmers_list, name='farmers_list'),
    path('farmers/create/', views.farmer_create, name='farmer_create'),
    path('farmers/<int:pk>/', views.farmer_detail, name='farmer_detail'),
    path('farmers/<int:pk>/edit/', views.farmer_edit, name='farmer_edit'),
    path('farmers/<int:pk>/delete/', views.farmer_delete, name='farmer_delete'),
    path('groups/', views.groups_list, name='groups_list'),
    path('groups/create/', views.group_create, name='group_create'),
    path('groups/<int:pk>/', views.group_detail, name='group_detail'),
    path('groups/<int:pk>/edit/', views.group_edit, name='group_edit'),
    path('groups/<int:pk>/delete/', views.group_delete, name='group_delete'),
    path('group-types/', views.group_types_list, name='group_types_list'),
    path('group-types/create/', views.group_type_create, name='group_type_create'),
    path('group-types/<int:pk>/', views.group_type_detail, name='group_type_detail'),
    path('group-types/<int:pk>/edit/', views.group_type_edit, name='group_type_edit'),
    path('group-types/<int:pk>/delete/', views.group_type_delete, name='group_type_delete'),
    path('vendors/', views.vendors_list, name='vendors_list'),
    path('vendors/create/', views.vendor_create, name='vendor_create'),
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor_detail'),
    path('vendors/<int:pk>/edit/', views.vendor_edit, name='vendor_edit'),
    path('vendors/<int:pk>/delete/', views.vendor_delete, name='vendor_delete'),
    path('redemption-centers/', views.redemption_centers_list, name='redemption_centers_list'),
    path('redemption-centers/create/', views.redemption_center_create, name='redemption_center_create'),
    path('redemption-centers/<int:pk>/', views.redemption_center_detail, name='redemption_center_detail'),
    path('redemption-centers/<int:pk>/edit/', views.redemption_center_edit, name='redemption_center_edit'),
    path('redemption-centers/<int:pk>/delete/', views.redemption_center_delete, name='redemption_center_delete'),
    path('incentives/', views.incentives_list, name='incentives_list'),
    path('incentives/create/', views.incentive_create, name='incentive_create'),
    path('incentives/<int:pk>/', views.incentive_detail, name='incentive_detail'),
    path('incentives/<int:pk>/edit/', views.incentive_edit, name='incentive_edit'),
    path('incentives/<int:pk>/delete/', views.incentive_delete, name='incentive_delete'),
    path('api/lgas/', views.get_lgas_by_state, name='get_lgas_by_state'),
]
