# Generated by Django 5.2.4 on 2025-11-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the group type (e.g., 'Cooperative', 'Association', 'Union')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this group type represents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group type is currently active')),
            ],
            options={
                'verbose_name': 'Group Type',
                'verbose_name_plural': 'Group Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Name of the farmer group', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is currently active')),
                ('group_type', models.ForeignKey(help_text='Select the type of group', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='farmers.grouptype')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group_type', 'is_active'], name='farmers_gro_group_t_c05ca9_idx'), models.Index(fields=['group_name'], name='farmers_gro_group_n_127bef_idx')],
            },
        ),
    ]
