# Generated by Django 5.2.4 on 2025-11-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptype',
            name='is_active',
        ),
    ]
