# Generated by Django 5.2.4 on 2025-11-16 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_grouptype_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Vendor ID')),
                ('vendor_firstname', models.CharField(help_text='First name of the vendor', max_length=100)),
                ('vendor_surname', models.CharField(help_text='Surname of the vendor', max_length=100)),
                ('vendor_middlename', models.CharField(blank=True, help_text='Middle name of the vendor', max_length=100)),
                ('vendor_company_name', models.CharField(help_text='Company or organization name', max_length=200)),
                ('vendor_address', models.TextField(help_text='Complete address of the vendor')),
                ('vendor_email_address', models.EmailField(help_text='Email address of the vendor', max_length=254, unique=True)),
                ('vendor_phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('vendor_registration_no', models.CharField(editable=False, help_text='6-digit registration number (automatically generated)', max_length=6, unique=True)),
                ('vendor_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the vendor', max_length=10)),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='Date and time when vendor was registered')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-date_registered'],
                'indexes': [models.Index(fields=['vendor_status', 'date_registered'], name='farmers_ven_vendor__7c707f_idx'), models.Index(fields=['vendor_email_address'], name='farmers_ven_vendor__8c628e_idx'), models.Index(fields=['vendor_registration_no'], name='farmers_ven_vendor__6a7d55_idx')],
            },
        ),
    ]
