# Generated by Django 5.2.4 on 2025-11-16 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Farmer ID')),
                ('firstname', models.CharField(help_text='First name of the farmer', max_length=100)),
                ('surname', models.CharField(help_text='Surname of the farmer', max_length=100)),
                ('middlename', models.CharField(blank=True, help_text='Middle name of the farmer', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the farmer', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the farmer', max_length=10)),
                ('NIN', models.CharField(blank=True, help_text='National Identification Number (11 digits)', max_length=11, null=True, unique=True)),
                ('BVN', models.CharField(blank=True, help_text='Bank Verification Number (11 digits)', max_length=11, null=True, unique=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text='Residential address of the farmer')),
                ('state', models.CharField(blank=True, help_text='State of residence', max_length=100)),
                ('LGA', models.CharField(blank=True, help_text='Local Government Area', max_length=100, verbose_name='LGA')),
                ('ward', models.CharField(blank=True, help_text='Ward', max_length=100)),
                ('farm_location', models.TextField(blank=True, help_text='Location of the farm')),
                ('group_leader_name', models.CharField(blank=True, help_text='Name of the group leader', max_length=200)),
                ('group_leader_phone', models.CharField(blank=True, help_text='Phone number of the group leader', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('crop', models.CharField(blank=True, help_text='Type of crop(s) the farmer grows', max_length=200)),
                ('picture', models.ImageField(blank=True, help_text='Picture of the farmer', null=True, upload_to='farmers/pictures/')),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='Date and time when farmer was registered')),
                ('farmer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the farmer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.ForeignKey(blank=True, help_text='Name of the group the farmer belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='farmers.group')),
                ('group_type', models.ForeignKey(blank=True, help_text='Type of group the farmer belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farmers.grouptype')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor who registered this farmer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to='farmers.vendor')),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-date_registered'],
                'indexes': [models.Index(fields=['surname', 'firstname'], name='farmers_far_surname_f0a980_idx'), models.Index(fields=['farmer_status', 'date_registered'], name='farmers_far_farmer__d9080a_idx'), models.Index(fields=['state', 'LGA'], name='farmers_far_state_cfafde_idx'), models.Index(fields=['NIN'], name='farmers_far_NIN_6fdbe6_idx'), models.Index(fields=['BVN'], name='farmers_far_BVN_d23cab_idx')],
            },
        ),
    ]
