# Generated by Django 5.2.4 on 2025-11-16 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionCenter',
            fields=[
                ('redemption_center_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Redemption Center ID')),
                ('fullname', models.CharField(help_text='Full name of the redemption center', max_length=200)),
                ('redemption_center_address', models.TextField(help_text='Complete address of the redemption center')),
                ('phone_no', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text='Email address of the redemption center', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redemption Center',
                'verbose_name_plural': 'Redemption Centers',
                'ordering': ['fullname'],
                'indexes': [models.Index(fields=['fullname'], name='farmers_red_fullnam_e2585b_idx'), models.Index(fields=['email'], name='farmers_red_email_f8bb17_idx')],
            },
        ),
    ]
