# Generated by Django 5.2.4 on 2025-11-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_redemptioncenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Local Government Area', max_length=100)),
            ],
            options={
                'verbose_name': 'Local Government Area',
                'verbose_name_plural': 'Local Government Areas',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the state', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='State code (e.g., LAG, ABJ)', max_length=3, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='farmer',
            new_name='farmers_far_state_i_8ebd13_idx',
            old_name='farmers_far_state_cfafde_idx',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='LGA',
            field=models.ForeignKey(blank=True, help_text='Local Government Area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farmers.lga', verbose_name='LGA'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(help_text='State this LGA belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='farmers.state'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farmers.state'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('name', 'state')},
        ),
    ]
