# Generated by Django 5.2.4 on 2025-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_lga_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='picture',
            field=models.ImageField(blank=True, help_text='Picture of the farmer', null=True, upload_to='farmers/'),
        ),
    ]
