# Generated by Django 5.2.4 on 2025-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_alter_farmer_picture'),
    ]

    operations = [
        # First, set a default value for existing NULL NIN values
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('farmers', 'Farmer').objects.filter(NIN__isnull=True).update(NIN='PENDING'),
            reverse_code=migrations.RunPython.noop,
        ),
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='farmer',
            name='NIN',
            field=models.CharField(help_text='National Identification Number (11 digits)', max_length=11, unique=True),
        ),
    ]
