# Generated by Django 5.2.4 on 2025-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_auto_20251116_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncenter',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the redemption center (optional)'),
        ),
    ]
