# Generated by Django 5.2.4 on 2025-11-16 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_redemptioncenter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('incentive_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Incentive ID')),
                ('incentive_name', models.CharField(help_text='Name of the incentive', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the incentive')),
                ('date_sent', models.DateField(default=django.utils.timezone.now, help_text='Date when the incentive was sent to the redemption center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redemption_center', models.ForeignKey(help_text='Redemption center where this incentive is allocated', on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='farmers.redemptioncenter')),
            ],
            options={
                'verbose_name': 'Incentive',
                'verbose_name_plural': 'Incentives',
                'ordering': ['-date_sent', '-created_at'],
                'indexes': [models.Index(fields=['date_sent', 'redemption_center'], name='farmers_inc_date_se_7c6683_idx'), models.Index(fields=['incentive_name'], name='farmers_inc_incenti_63b836_idx')],
            },
        ),
    ]
