# Generated by Django 5.2.4 on 2025-11-16 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the incentive (optional)'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='date_sent',
            field=models.DateField(default=datetime.date.today, help_text='Date when the incentive was sent to the redemption center'),
        ),
    ]
