# Generated by Django 5.2.4 on 2025-11-17 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_incentive_description_alter_incentive_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_leader',
            field=models.ForeignKey(blank=True, help_text='Select the group leader from available farmers (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='farmers.farmer'),
        ),
    ]
