# Generated by Django 5.2.4 on 2025-11-17 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_group_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='group_leader_phone',
            field=models.CharField(blank=True, help_text='Phone number of the group leader', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (7-20 characters, digits, spaces, dashes, parentheses, or + allowed).', regex='^[\\d\\s\\-\\+\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (7-20 characters, digits, spaces, dashes, parentheses, or + allowed).', regex='^[\\d\\s\\-\\+\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (7-20 characters, digits, spaces, dashes, parentheses, or + allowed).', regex='^[\\d\\s\\-\\+\\(\\)]{7,20}$')]),
        ),
    ]
