# Generated by Django 5.2.4 on 2025-11-17 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_alter_farmer_group_leader_phone_alter_farmer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptioncenter',
            name='phone_no',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (7-20 characters, digits, spaces, dashes, parentheses, or + allowed).', regex='^[\\d\\s\\-\\+\\(\\)]{7,20}$')]),
        ),
    ]
