# Generated by Django 5.2.4 on 2025-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0015_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncenter',
            name='redemption_center_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the redemption center', max_length=10),
        ),
        migrations.AddIndex(
            model_name='redemptioncenter',
            index=models.Index(fields=['redemption_center_status'], name='farmers_red_redempt_b8f8c9_idx'),
        ),
    ]
