# Generated by Django 5.2.4 on 2025-11-19 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0016_redemptioncenter_redemption_center_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncenter',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django User account for redemption center login credentials', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemption_center_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
