# Generated by Django 5.2.4 on 2025-11-20 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0017_redemptioncenter_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('disbursement_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Disbursement ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of incentive disbursed to the farmer')),
                ('disbursement_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the disbursement was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this disbursement (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_by', models.ForeignKey(blank=True, help_text='User who processed this disbursement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(help_text='Farmer receiving the incentive', on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='farmers.farmer')),
                ('incentive', models.ForeignKey(help_text='Incentive being disbursed', on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='farmers.incentive')),
                ('redemption_center', models.ForeignKey(help_text='Redemption center that disbursed this incentive', on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='farmers.redemptioncenter')),
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'ordering': ['-disbursement_date'],
                'indexes': [models.Index(fields=['incentive', 'farmer'], name='farmers_dis_incenti_59c5a9_idx'), models.Index(fields=['redemption_center', 'disbursement_date'], name='farmers_dis_redempt_0d9625_idx'), models.Index(fields=['farmer', 'disbursement_date'], name='farmers_dis_farmer__c99d10_idx')],
                'unique_together': {('incentive', 'farmer')},
            },
        ),
    ]
