# Generated by Django 5.2.4 on 2026-04-02 19:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0018_disbursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptioncenter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='redemption_center',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='redemption_center',
        ),
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['-date_created', '-created_at'], 'verbose_name': 'Incentive', 'verbose_name_plural': 'Incentives'},
        ),
        # Use SeparateDatabaseAndState so the migration state is updated
        # without executing SQL (the indexes may not exist in SQLite).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='disbursement',
                    name='farmers_dis_redempt_0d9625_idx',
                ),
                migrations.RemoveIndex(
                    model_name='incentive',
                    name='farmers_inc_date_se_7c6683_idx',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='incentive',
            name='date_created',
            field=models.DateField(default=datetime.date.today, help_text='Date when the incentive batch was created'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who processed this disbursement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Total quantity of this incentive batch'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['disbursement_date'], name='farmers_dis_disburs_1c39f5_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['date_created'], name='farmers_inc_date_cr_e0e860_idx'),
        ),
        migrations.DeleteModel(
            name='RedemptionCenter',
        ),
    ]
